// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package tag

import (
	"errors"
	"fmt"
)

const (
	// TagTypeEnumBoolean is a TagTypeEnum of type Boolean.
	TagTypeEnumBoolean TagTypeEnum = iota
	// TagTypeEnumInteger is a TagTypeEnum of type Integer.
	TagTypeEnumInteger
	// TagTypeEnumFloat is a TagTypeEnum of type Float.
	TagTypeEnumFloat
	// TagTypeEnumString is a TagTypeEnum of type String.
	TagTypeEnumString
)

var ErrInvalidTagTypeEnum = errors.New("not a valid TagTypeEnum")

const _TagTypeEnumName = "BooleanIntegerFloatString"

var _TagTypeEnumMap = map[TagTypeEnum]string{
	TagTypeEnumBoolean: _TagTypeEnumName[0:7],
	TagTypeEnumInteger: _TagTypeEnumName[7:14],
	TagTypeEnumFloat:   _TagTypeEnumName[14:19],
	TagTypeEnumString:  _TagTypeEnumName[19:25],
}

// String implements the Stringer interface.
func (x TagTypeEnum) String() string {
	if str, ok := _TagTypeEnumMap[x]; ok {
		return str
	}
	return fmt.Sprintf("TagTypeEnum(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TagTypeEnum) IsValid() bool {
	_, ok := _TagTypeEnumMap[x]
	return ok
}

var _TagTypeEnumValue = map[string]TagTypeEnum{
	_TagTypeEnumName[0:7]:   TagTypeEnumBoolean,
	_TagTypeEnumName[7:14]:  TagTypeEnumInteger,
	_TagTypeEnumName[14:19]: TagTypeEnumFloat,
	_TagTypeEnumName[19:25]: TagTypeEnumString,
}

// ParseTagTypeEnum attempts to convert a string to a TagTypeEnum.
func ParseTagTypeEnum(name string) (TagTypeEnum, error) {
	if x, ok := _TagTypeEnumValue[name]; ok {
		return x, nil
	}
	return TagTypeEnum(0), fmt.Errorf("%s is %w", name, ErrInvalidTagTypeEnum)
}
