// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package tag

import (
	"errors"
	"fmt"
)

const (
	// TagQualityEnumBad is a TagQualityEnum of type Bad.
	TagQualityEnumBad TagQualityEnum = iota
	// TagQualityEnumUncertain is a TagQualityEnum of type Uncertain.
	TagQualityEnumUncertain
	// TagQualityEnumGood is a TagQualityEnum of type Good.
	TagQualityEnumGood
	// TagQualityEnumSimulated is a TagQualityEnum of type Simulated.
	TagQualityEnumSimulated
)

var ErrInvalidTagQualityEnum = errors.New("not a valid TagQualityEnum")

const _TagQualityEnumName = "BadUncertainGoodSimulated"

var _TagQualityEnumMap = map[TagQualityEnum]string{
	TagQualityEnumBad:       _TagQualityEnumName[0:3],
	TagQualityEnumUncertain: _TagQualityEnumName[3:12],
	TagQualityEnumGood:      _TagQualityEnumName[12:16],
	TagQualityEnumSimulated: _TagQualityEnumName[16:25],
}

// String implements the Stringer interface.
func (x TagQualityEnum) String() string {
	if str, ok := _TagQualityEnumMap[x]; ok {
		return str
	}
	return fmt.Sprintf("TagQualityEnum(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TagQualityEnum) IsValid() bool {
	_, ok := _TagQualityEnumMap[x]
	return ok
}

var _TagQualityEnumValue = map[string]TagQualityEnum{
	_TagQualityEnumName[0:3]:   TagQualityEnumBad,
	_TagQualityEnumName[3:12]:  TagQualityEnumUncertain,
	_TagQualityEnumName[12:16]: TagQualityEnumGood,
	_TagQualityEnumName[16:25]: TagQualityEnumSimulated,
}

// ParseTagQualityEnum attempts to convert a string to a TagQualityEnum.
func ParseTagQualityEnum(name string) (TagQualityEnum, error) {
	if x, ok := _TagQualityEnumValue[name]; ok {
		return x, nil
	}
	return TagQualityEnum(0), fmt.Errorf("%s is %w", name, ErrInvalidTagQualityEnum)
}
