// Code generated by "enumer -type=TagKind -trimprefix=TagKind -json"; DO NOT EDIT.

package tag

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TagKindName = "BooleanInteger"

var _TagKindIndex = [...]uint8{0, 7, 14}

const _TagKindLowerName = "booleaninteger"

func (i TagKind) String() string {
	if i < 0 || i >= TagKind(len(_TagKindIndex)-1) {
		return fmt.Sprintf("TagKind(%d)", i)
	}
	return _TagKindName[_TagKindIndex[i]:_TagKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TagKindNoOp() {
	var x [1]struct{}
	_ = x[TagKindBoolean-(0)]
	_ = x[TagKindInteger-(1)]
}

var _TagKindValues = []TagKind{TagKindBoolean, TagKindInteger}

var _TagKindNameToValueMap = map[string]TagKind{
	_TagKindName[0:7]:       TagKindBoolean,
	_TagKindLowerName[0:7]:  TagKindBoolean,
	_TagKindName[7:14]:      TagKindInteger,
	_TagKindLowerName[7:14]: TagKindInteger,
}

var _TagKindNames = []string{
	_TagKindName[0:7],
	_TagKindName[7:14],
}

// TagKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TagKindString(s string) (TagKind, error) {
	if val, ok := _TagKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TagKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TagKind values", s)
}

// TagKindValues returns all values of the enum
func TagKindValues() []TagKind {
	return _TagKindValues
}

// TagKindStrings returns a slice of all String values of the enum
func TagKindStrings() []string {
	strs := make([]string, len(_TagKindNames))
	copy(strs, _TagKindNames)
	return strs
}

// IsATagKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TagKind) IsATagKind() bool {
	for _, v := range _TagKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TagKind
func (i TagKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TagKind
func (i *TagKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TagKind should be a string, got %s", data)
	}

	var err error
	*i, err = TagKindString(s)
	return err
}
