// Code generated by "enumer -type=TagQuality -trimprefix=TagQuality -json"; DO NOT EDIT.

package tag

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TagQualityName = "UnknownBadUncertainGoodSimulated"

var _TagQualityIndex = [...]uint8{0, 7, 10, 19, 23, 32}

const _TagQualityLowerName = "unknownbaduncertaingoodsimulated"

func (i TagQuality) String() string {
	if i < 0 || i >= TagQuality(len(_TagQualityIndex)-1) {
		return fmt.Sprintf("TagQuality(%d)", i)
	}
	return _TagQualityName[_TagQualityIndex[i]:_TagQualityIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TagQualityNoOp() {
	var x [1]struct{}
	_ = x[TagQualityUnknown-(0)]
	_ = x[TagQualityBad-(1)]
	_ = x[TagQualityUncertain-(2)]
	_ = x[TagQualityGood-(3)]
	_ = x[TagQualitySimulated-(4)]
}

var _TagQualityValues = []TagQuality{TagQualityUnknown, TagQualityBad, TagQualityUncertain, TagQualityGood, TagQualitySimulated}

var _TagQualityNameToValueMap = map[string]TagQuality{
	_TagQualityName[0:7]:        TagQualityUnknown,
	_TagQualityLowerName[0:7]:   TagQualityUnknown,
	_TagQualityName[7:10]:       TagQualityBad,
	_TagQualityLowerName[7:10]:  TagQualityBad,
	_TagQualityName[10:19]:      TagQualityUncertain,
	_TagQualityLowerName[10:19]: TagQualityUncertain,
	_TagQualityName[19:23]:      TagQualityGood,
	_TagQualityLowerName[19:23]: TagQualityGood,
	_TagQualityName[23:32]:      TagQualitySimulated,
	_TagQualityLowerName[23:32]: TagQualitySimulated,
}

var _TagQualityNames = []string{
	_TagQualityName[0:7],
	_TagQualityName[7:10],
	_TagQualityName[10:19],
	_TagQualityName[19:23],
	_TagQualityName[23:32],
}

// TagQualityString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TagQualityString(s string) (TagQuality, error) {
	if val, ok := _TagQualityNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TagQualityNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TagQuality values", s)
}

// TagQualityValues returns all values of the enum
func TagQualityValues() []TagQuality {
	return _TagQualityValues
}

// TagQualityStrings returns a slice of all String values of the enum
func TagQualityStrings() []string {
	strs := make([]string, len(_TagQualityNames))
	copy(strs, _TagQualityNames)
	return strs
}

// IsATagQuality returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TagQuality) IsATagQuality() bool {
	for _, v := range _TagQualityValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TagQuality
func (i TagQuality) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TagQuality
func (i *TagQuality) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TagQuality should be a string, got %s", data)
	}

	var err error
	*i, err = TagQualityString(s)
	return err
}
