// Code generated by "enumer -type=TagType -trimprefix=TagType -json"; DO NOT EDIT.

package tag

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _TagTypeName = "UnknownBooleanInteger"

var _TagTypeIndex = [...]uint8{0, 7, 14, 21}

const _TagTypeLowerName = "unknownbooleaninteger"

func (i TagType) String() string {
	if i < 0 || i >= TagType(len(_TagTypeIndex)-1) {
		return fmt.Sprintf("TagType(%d)", i)
	}
	return _TagTypeName[_TagTypeIndex[i]:_TagTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TagTypeNoOp() {
	var x [1]struct{}
	_ = x[TagTypeUnknown-(0)]
	_ = x[TagTypeBoolean-(1)]
	_ = x[TagTypeInteger-(2)]
}

var _TagTypeValues = []TagType{TagTypeUnknown, TagTypeBoolean, TagTypeInteger}

var _TagTypeNameToValueMap = map[string]TagType{
	_TagTypeName[0:7]:        TagTypeUnknown,
	_TagTypeLowerName[0:7]:   TagTypeUnknown,
	_TagTypeName[7:14]:       TagTypeBoolean,
	_TagTypeLowerName[7:14]:  TagTypeBoolean,
	_TagTypeName[14:21]:      TagTypeInteger,
	_TagTypeLowerName[14:21]: TagTypeInteger,
}

var _TagTypeNames = []string{
	_TagTypeName[0:7],
	_TagTypeName[7:14],
	_TagTypeName[14:21],
}

// TagTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TagTypeString(s string) (TagType, error) {
	if val, ok := _TagTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TagTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TagType values", s)
}

// TagTypeValues returns all values of the enum
func TagTypeValues() []TagType {
	return _TagTypeValues
}

// TagTypeStrings returns a slice of all String values of the enum
func TagTypeStrings() []string {
	strs := make([]string, len(_TagTypeNames))
	copy(strs, _TagTypeNames)
	return strs
}

// IsATagType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TagType) IsATagType() bool {
	for _, v := range _TagTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TagType
func (i TagType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TagType
func (i *TagType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TagType should be a string, got %s", data)
	}

	var err error
	*i, err = TagTypeString(s)
	return err
}
