// Command growscada_device_simulator simulates one lower-level Device: it writes Tag
// values generated by patterns to a GrowSCADA server and serves a control API.
package main

import (
	"context"
	"errors"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/alexflint/go-arg"

	"github.com/kipitix/growscada/internal/apiclient"
	"github.com/kipitix/growscada/internal/devicelink"
	"github.com/kipitix/growscada/internal/devicesim"
)

type simulatorArgs struct {
	Config         string        `arg:"--config,required" help:"YAML config of the simulated device"`
	Server         string        `arg:"--server,env:DEVSIM_SERVER" help:"GrowSCADA REST API URL; overrides the config"`
	Control        string        `arg:"--control" help:"control API listen address; overrides the config"`
	StartupTimeout time.Duration `arg:"--startup-timeout" default:"30s" help:"how long to wait for the server at startup"`
}

func main() {
	var args simulatorArgs
	arg.MustParse(&args)
	if err := run(args); err != nil {
		slog.Error("device simulator failed", "error", err)
		os.Exit(1)
	}
}

func run(args simulatorArgs) error {
	f, err := os.Open(args.Config)
	if err != nil {
		return err
	}
	cfg, err := devicesim.ReadConfig(f)
	f.Close()
	if err != nil {
		return err
	}
	if args.Server != "" {
		cfg.Server = args.Server
	}
	if args.Control != "" {
		cfg.Control = args.Control
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	link := devicelink.NewRESTLink(apiclient.New(cfg.Server, &http.Client{Timeout: 10 * time.Second}))
	device, err := devicesim.Open(ctx, cfg, link, devicesim.Options{StartupTimeout: args.StartupTimeout})
	if err != nil {
		return err
	}

	listener, err := net.Listen("tcp", cfg.Control)
	if err != nil {
		return err
	}
	control := &http.Server{Handler: device.Handler()}
	go func() {
		if err := control.Serve(listener); err != nil && !errors.Is(err, http.ErrServerClosed) {
			slog.Error("control API failed", "error", err)
			stop()
		}
	}()
	slog.Info("device simulator started", "server", cfg.Server, "control", listener.Addr().String(),
		"tags", len(cfg.Tags), "running", device.Status().Running)

	device.Run(ctx)

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	slog.Info("device simulator stopping")
	return control.Shutdown(shutdownCtx)
}
