package restapi

import (
	"encoding/json"
	"fmt"
	"net/http"
)

// ProblemDetails implements RFC 9457
// https://www.rfc-editor.org/rfc/rfc9457.html
type ProblemDetails struct {
	// Type - URI reference identifying the problem type.
	// REQUIRED. Must link to human-readable documentation.
	Type string `json:"type"`

	// Title - short, human-readable summary of the problem type.
	// REQUIRED. Should not change between occurrences.
	Title string `json:"title"`

	// Status - HTTP status code generated by the origin server.
	// REQUIRED. MUST match the HTTP response status code.
	Status int `json:"status"`

	// Detail - human-readable explanation specific to this occurrence.
	// OPTIONAL. Helps the client understand the error.
	Detail string `json:"detail,omitempty"`

	// Instance - URI reference identifying the specific occurrence.
	// OPTIONAL. Can be used to look up the problem in logs.
	Instance string `json:"instance,omitempty"`

	// Extensions - additional problem details (RFC 9457 allows custom fields).
	// MUST NOT override the standard fields above.
	Extensions map[string]interface{} `json:"-"`
}

// MarshalJSON implements custom marshaling for extensions
func (p ProblemDetails) MarshalJSON() ([]byte, error) {
	// Build a map for the base fields
	result := map[string]interface{}{
		"type":   p.Type,
		"title":  p.Title,
		"status": p.Status,
	}

	// Add optional fields if present
	if p.Detail != "" {
		result["detail"] = p.Detail
	}
	if p.Instance != "" {
		result["instance"] = p.Instance
	}

	// Merge extensions
	for k, v := range p.Extensions {
		// Prevent overriding standard fields
		if _, exists := result[k]; !exists {
			result[k] = v
		}
	}

	return json.Marshal(result)
}

// UnmarshalJSON implements custom unmarshaling for extensions
func (p *ProblemDetails) UnmarshalJSON(data []byte) error {
	// Unmarshal into a map first to capture extensions
	var raw map[string]interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Extract standard fields
	if v, ok := raw["type"].(string); ok {
		p.Type = v
		delete(raw, "type")
	}
	if v, ok := raw["title"].(string); ok {
		p.Title = v
		delete(raw, "title")
	}
	if v, ok := raw["status"].(float64); ok {
		p.Status = int(v)
		delete(raw, "status")
	}
	if v, ok := raw["detail"].(string); ok {
		p.Detail = v
		delete(raw, "detail")
	}
	if v, ok := raw["instance"].(string); ok {
		p.Instance = v
		delete(raw, "instance")
	}

	// Everything else is an extension
	if len(raw) > 0 {
		p.Extensions = raw
	}

	return nil
}

// Base problem type URIs
const (
	// Base URI for problem types
	BaseTypeURI = "https://api.growscada.com/errors/"

	// Standard problem types
	TypeBadRequest      = BaseTypeURI + "bad-request"
	TypeUnauthorized    = BaseTypeURI + "unauthorized"
	TypeForbidden       = BaseTypeURI + "forbidden"
	TypeNotFound        = BaseTypeURI + "not-found"
	TypeConflict        = BaseTypeURI + "conflict"
	TypeValidation      = BaseTypeURI + "validation-error"
	TypeTooManyRequests = BaseTypeURI + "too-many-requests"
	TypeInternalError   = BaseTypeURI + "internal-error"
	TypeUnavailable     = BaseTypeURI + "service-unavailable"
)

// Common problem creators
func NewBadRequest(detail, instance string) *ProblemDetails {
	return &ProblemDetails{
		Type:     TypeBadRequest,
		Title:    "Bad Request",
		Status:   http.StatusBadRequest, //400
		Detail:   detail,
		Instance: instance,
	}
}

func NewNotFound(resourceType, resourceID, instance string) *ProblemDetails {
	detail := fmt.Sprintf("%s with ID '%s' not found", resourceType, resourceID)
	return &ProblemDetails{
		Type:     TypeNotFound,
		Title:    "Resource Not Found",
		Status:   http.StatusNotFound, //404
		Detail:   detail,
		Instance: instance,
	}
}

func NewConflict(resource, detail, instance string) *ProblemDetails {
	return &ProblemDetails{
		Type:     TypeConflict,
		Title:    fmt.Sprintf("Conflict: %s", resource),
		Status:   http.StatusConflict, //409
		Detail:   detail,
		Instance: instance,
	}
}

func NewValidationError(validationErrors map[string][]string, instance string) *ProblemDetails {
	return &ProblemDetails{
		Type:     TypeValidation,
		Title:    "Validation Error",
		Status:   http.StatusUnprocessableEntity, // 422
		Detail:   "Request validation failed",
		Instance: instance,
		Extensions: map[string]interface{}{
			"errors": validationErrors,
		},
	}
}

func NewInternalError(detail, instance string) *ProblemDetails {
	return &ProblemDetails{
		Type:     TypeInternalError,
		Title:    "Internal Server Error",
		Status:   http.StatusInternalServerError, // 500
		Detail:   detail,
		Instance: instance,
	}
}
